---
# This playbook will build docker image and push onto registry.
- name: Docker build and push
  hosts: localhost
  vars_files:
    - vars/access.yml
  become: true

  roles:
    - login
    - pull
    - build
