# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
     runs-on: ubuntu-latest
#    container:
#      image: lucasalt/act_base:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: roles-ansible/check-ansible-ubuntu-latest-action@master
      - name: Code pull
        run: |
          ls -l
          docker --version
          ansible-playbook -i ./ansible/host.yml ./ansible/site.yml
      
      - name: ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: './ansible/site.yml'
          inventoryFile: './ansible/host.yml'
          rolesPath: "./ansible/playbooks/roles"
          keyFile: "ec2.pem"
          verbosity: "vv"
          extraVars: "-e build_number=${{ github.run_id }}"
