# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Code pull
        run: |
          ls -l
          docker --version
          echo ${{ github.run_id }}
          ansible-playbook -i ./ansible/host.yml ./ansible/site.yml --extra-vars "${{ github.run_id }}=run_id"
      
      - name: ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: './ansible/site.yml'
          inventoryFile: './ansible/host.yml'
          rolesPath: "./ansible/playbooks/roles"
          keyFile: "ec2.pem"
          verbosity: "vv"
          extraVars: "-e build_number=${{ github.run_id }}"
